# Numpy Syntax

## Import Numpy

In [ ]:
# Import numpy
import numpy as np

## Numpy Array

In [ ]:
# Python list
python_list = [1,2,3]
print(type(python_list))

<class 'list'>


In [ ]:
# Numpy Array
numpy_array = np.array(python_list)
print(numpy_array)
print(type(numpy_array))

[1 2 3]
<class 'numpy.ndarray'>


In [ ]:
# Matrix
numpy_matrix = np.matrix([[1,2,3],[4,5,6]])
print(numpy_matrix)
print(type(numpy_matrix))

[[1 2 3]
 [4 5 6]]
<class 'numpy.matrix'>


In [ ]:
# arange
one_to_ten = np.arange(1,11)
print(one_to_ten)
one_to_ten_with_step = np.arange(1,11,3)
print(one_to_ten_with_step)

[ 1  2  3  4  5  6  7  8  9 10]
[ 1  4  7 10]


In [ ]:
# ones, zeros, eye
ones_ex = np.ones(5) # filled with 1s
zeros_ex = np.zeros(5) # filled with 0s
eye_ex = np.eye(5) # Identity Matrix
print(ones_ex)
print(zeros_ex)
print(eye_ex)

[1. 1. 1. 1. 1.]
[0. 0. 0. 0. 0.]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [ ]:
# random.rand
random_array = np.random.rand(5,10)
print(random_array)
print(random_array.shape)

[[0.53429405 0.18485563 0.63997179 0.93038279 0.40535084 0.86362807
  0.33410863 0.5644295  0.01546389 0.92104026]
 [0.12259153 0.19850534 0.86444829 0.86664204 0.61860511 0.35342317
  0.72428406 0.24619028 0.55453856 0.85879442]
 [0.64384127 0.52626167 0.92895097 0.43594046 0.20074973 0.47733571
  0.19689226 0.22511581 0.67055502 0.07756007]
 [0.04296716 0.41078291 0.06389432 0.59623517 0.11036265 0.47168511
  0.15217717 0.69348863 0.06645151 0.28712274]
 [0.96249941 0.02733648 0.80217918 0.56014755 0.8030844  0.21074387
  0.96819377 0.70358261 0.45844447 0.23863957]]
(5, 10)


In [ ]:
# 5x5 matrix with random integer from 1 to 10
randomint_array = np.random.randint(1,10,(5,5))
print(randomint_array)

[[46 85 60 17 25]
 [73 92 49 70 52]
 [40 11 52 40 54]
 [86 40 36 36 70]
 [26 90 16 16 50]]


In [ ]:
# reshape
original_array = np.arange(1,17)
reshaped_array = original_array.reshape(4,4)
print(original_array)
print(reshaped_array)
print(reshaped_array.shape)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
(4, 4)


## Numpy Indexing & Selecting

In [ ]:
np_arr = np.arange(1,11)
print(np_arr)
print(np_arr[1:5]) # 2,3,4,5
np_arr_2d = np.random.randint(1,10,(5,5))
print("\n 2D: \n", np_arr_2d)
print(np_arr_2d[0]) # first row
print(np_arr_2d[0,2]) # fist row, second column

[ 1  2  3  4  5  6  7  8  9 10]
[2 3 4 5]

 2D: 
 [[9 9 6 4 7]
 [3 9 2 8 2]
 [2 7 2 2 5]
 [5 1 1 9 6]
 [7 3 5 7 2]]
[9 9 6 4 7]
6


In [ ]:
np_arr_select = np.array([10,20,-1,-2,-30])
print(np_arr_select[np_arr_select > 0])
print(np_arr_select[np_arr_select % 2 == 0])

[10 20]
[ 10  20  -2 -30]


## Numpy Operation

In [ ]:
np_arr_operation = np.array([2,4,6,8,10,-100,-2])
print(np_arr_operation.sum())
print(np_arr_operation.max())
print(np_arr_operation.min())
print(np_arr_operation.mean())

-72
10
-100
-10.285714285714286


# Coding Challenge (Numpy)

## Design a Python function using NumPy to help a small business track its weekly sales. The business sells three different products, and the sales data is stored in a 2D array where each row represents a day of the week (Monday to Friday), and each column represents one of the products. Your function should calculate the total for each day and store it in a 1D Array

Hint: row is axis = 1 in numpy solution

In [ ]:
import numpy as np

# Sample data: rows are days, columns are products
sales_data = np.array([
    [10, 15, 20],  # Monday's sales for Product 1, 2, 3
    [25, 30, 35],  # Tuesday's sales for Product 1, 2, 3
    [45, 20, 10],  # Wednesday's sales for Product 1, 2, 3
    [50, 50, 50],  # Thursday's sales for Product 1, 2, 3
    [12, 20, 10]   # Friday's sales for Product 1, 2, 3
])
total_sales_each_day = np.zeros(5) # [0,0,0,0,0]

def analyze_sales(data):
    # Your code here to calculate daily totals
    return total_sales_each_day

# Example call to your function
print(analyze_sales(sales_data))


[0. 0. 0. 0. 0.]


## Solution Below: SPOLER ALERT (Brute Force vs Cleaner vs Numpy Way)



In [ ]:
# Sample data: rows are days, columns are products
sales_data = np.array([
    [10, 15, 20],  # Monday's sales for Product 1, 2, 3
    [25, 30, 35],  # Tuesday's sales for Product 1, 2, 3
    [45, 20, 10],  # Wednesday's sales for Product 1, 2, 3
    [50, 50, 50],  # Thursday's sales for Product 1, 2, 3
    [12, 20, 10]   # Friday's sales for Product 1, 2, 3
])
total_sales_each_day = np.zeros(5) # [0,0,0,0,0]

def analyze_sales(data):
    # Calculate each sum of each row
    total_sales_each_day[0] = sales_data[0].sum()
    total_sales_each_day[1] = sales_data[1].sum()
    total_sales_each_day[2] = sales_data[2].sum()
    total_sales_each_day[3] = sales_data[3].sum()
    total_sales_each_day[4] = sales_data[4].sum()
    return total_sales_each_day

# Example call to your function
print(analyze_sales(sales_data))

[ 45.  90.  75. 150.  42.]


In [ ]:
# Sample data: rows are days, columns are products
sales_data = np.array([
    [10, 15, 20],  # Monday's sales for Product 1, 2, 3
    [25, 30, 35],  # Tuesday's sales for Product 1, 2, 3
    [45, 20, 10],  # Wednesday's sales for Product 1, 2, 3
    [50, 50, 50],  # Thursday's sales for Product 1, 2, 3
    [12, 20, 10]   # Friday's sales for Product 1, 2, 3
])
total_sales_each_day = np.zeros(5) # [0,0,0,0,0]

def analyze_sales(data):
    # Loop through and calculate sum of each row
    for idx,element in enumerate(sales_data):
      total_sales_each_day[idx] = sales_data[idx].sum()
    return total_sales_each_day

# Example call to your function
print(analyze_sales(sales_data))

[ 45.  90.  75. 150.  42.]


In [ ]:
# Sample data: rows are days, columns are products
sales_data = np.array([
    [10, 15, 20],  # Monday's sales for Product 1, 2, 3
    [25, 30, 35],  # Tuesday's sales for Product 1, 2, 3
    [45, 20, 10],  # Wednesday's sales for Product 1, 2, 3
    [50, 50, 50],  # Thursday's sales for Product 1, 2, 3
    [12, 20, 10]   # Friday's sales for Product 1, 2, 3
])
total_sales_each_day = np.zeros(5) # [0,0,0,0,0]

def analyze_sales(data):
    # Using np.sum()
    total_sales_each_day = np.sum(sales_data, axis = 1)
    return total_sales_each_day

# Example call to your function
print(analyze_sales(sales_data))

[ 45  90  75 150  42]
